version: '3.8'
services:
  db1:
    image: postgres
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=dbuser1
      - POSTGRES_PASSWORD=dbpass1
    ports:
      - 5441:5432
    volumes:
      - ./db_primary.sql:/docker-entrypoint-initdb.d/init.sql
  # Notice I don't even use a volume here since I don't care to persist test data between runs
  db2:
    image: postgres
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=dbuser2
      - POSTGRES_PASSWORD=dbpass2
    ports:
      - 5442:5432
    volumes:
      - ./db_secondary.sql:/docker-entrypoint-initdb.d/init.sql
    # Notice I don't even use a volume here since I don't care to persist test data between runsS